### ISSUE TITLE
Warning: Cannot read property 'orig' of undefined

### ISSUE THREAD

**Issue by thoroughlydecent** [nopr/sassdown#77]
Hi

just trying out for the first time but getting this error

    Warning: Cannot read property 'orig' of undefined Use --force to continue.

Any thoughts?

Cheers

**Comment by nopr** [comment]
Sounds like files aren't being globbed; the `undefined` might be the files array it's trying to find the original src directory of. Can you describe (or paste) the configuration you currently have?

**Comment by thoroughlydecent** [comment]
Hi, 

here you go

       sassdown: {
            styleguide: {
                options: {
                    assets: ['docroot/assets/css/production/HNstyle.css']
                },
                files: [{
                    expand: true,
                    cwd: 'src/scss/**',
                    src: ['*.scss'],
                    dest: 'public/styleguide/'
                }]
            }
        },

**Comment by nopr** [comment]
@thoroughlydecent, the issue is your globbing pattern (`cwd: 'src/scss/**',`). If you want all .scss files within src/scss/ then it should be `'src/scss'`. If you want all .scss files within that entire directory tree, then you can set the `src` property to `['**/*.scss']`.

**Comment by thoroughlydecent** [comment]
of course it is!

thanks very much (I am very out of practice).

**Comment by nopr** [comment]
Not a problem!
