### ISSUE TITLE
Unable to nest markdown in comments.

### ISSUE THREAD

**Issue by joefritz** [nopr/sassdown#80]
Working on documenting within comments and noticed a problem with rendering.

    <div class="twelve sample">Twelve Columns</div>

Works just fine, but if I try to do

    <div class="row">
    <div class="twelve sample">Twelve Columns</div>
    </div>

I see the wrapping div rendered as text in my styleguide, it doesn't compile to HTML.  Here's a screenshot.

![screen shot 2015-02-12 at 2 27 04 pm](https://cloud.githubusercontent.com/assets/164233/6175283/45ffdbd2-b2c3-11e4-9f12-ca9aa015cbe1.png)

**Comment by nopr** [comment]
Hi @joefritz. I've just tested this and cannot replicate; can you paste the entire comment block you're using, please?

**Comment by joefritz** [comment]
Hi @nopr,

I managed to solve the problem by including three ``` marks inside of my comment before and after the markup.  I can still recreate the problem though, without the ticks, with the following LESS file:  http://cl.ly/3U0L1z14441d

That generates a styleguide that looks like this (I've done some theme customization):

![screen shot 2015-02-14 at 11 59 56 am](https://cloud.githubusercontent.com/assets/164233/6200338/28fc668e-b441-11e4-8de7-4e3c35eaa349.png)

Love sassdown, btw.  We've tried out every other grunt styleguide generator and this one is by far the best/most flexible.  Thanks for the hard work!

**Comment by nopr** [comment]
I've noticed from your example file that you're using tabs instead of spaces for indentation. This could be causing the problem. But yes, as you've found, generally using the fences (```) is a more reliable method of encapsulating code blocks.
