### ISSUE TITLE
Independent code comments separate from regular css comments

### ISSUE THREAD

**Issue by tgdev** [nopr/sassdown#87]
Sassdown is great however, if I have a regular css comment (/* ... */) in either a sass partial file I've created or a 3rd party sass partial I'm importing, sassdown assumes this is a module for the styleguide.

The two should be independent of each other with regular css comments being ignored by sassdown.

**Comment by nopr** [comment]
If regular (block-level) CSS comments are ignored by Sassdown, this would make it significantly more difficult to author longer and more detailed descriptions, examples, and notes in partials.

Two things:

1. Don't forget that you can define your own opening and closing comment syntax for Sassdown to parse. See the Grunt options in the README.

2. You can also use the glob array in `files` to exclude certain filenames or directories, if there is code you wish to ignore.

Unless either of the two solutions presents a problem, I'm closing this ticket.

**Comment by tgdev** [comment]
Yes it's fine to close this ticket. My apologies as I had overlooked the option to specify the opening and closing comment syntax.
